{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubechat.serviceAccountName" . }}
  namespace: {{ template "kubechat.namespace" . }}
  labels:
{{ include "kubechat.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubechat.serviceAccountName" . }}
  labels:
{{ include "kubechat.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "extensions", "apps", "batch", "events", "resourcequotas"]
    resources: ["*"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubechat.serviceAccountName" . }}
  labels:
{{ include "kubechat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubechat.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubechat.serviceAccountName" . }}
    namespace: {{ template "kubechat.namespace" . }}
{{- end -}}
